name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: xmake
      run: |
        echo "ubuntu version"
        lsb_release -a
        hostnamectl
        sudo apt update
        sudo apt install xmake python3-dev python3-venv python3-pip unzip p7zip -y
        export CMAKE_POLICY_VERSION_MINIMUM=3.5
        mkdir build
        xmake -y
        xmake project -k cmake -y
